//! The media's package set and its metadata.
//!
//! Which packages have to be replaced is NOT a list anyone maintains. It is
//! every package on the media whose `SOURCERPM` is the kernel SRPM, read out of
//! the repository metadata. On the 6.12.109-3 aarch64 media that is eight
//! packages, and the eighth is `bpftool` - which is not called `linux-`
//! anything and would be missed by any name-based rule. Leaving it behind
//! breaks the repo, because it carries `Requires: linux-tools = V-R` against a
//! version that no longer exists on the media.
//!
//! The metadata is regenerated over an OVERLAY of the read-only ISO tree, so
//! the input is never modified and the 1567 untouched packages are not copied.

use super::{ok, run, Ctx};
use crate::kconfig;
use std::fs;
use std::path::{Path, PathBuf};

/// One package as the media's `primary.xml` describes it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MediaPkg {
    pub name: String,
    /// `aarch64/linux-6.12.109-3.ph5.aarch64.rpm`, relative to /RPMS.
    pub href: String,
    pub sourcerpm: String,
    pub version: String,
    pub release: String,
}

impl MediaPkg {
    pub fn basename(&self) -> String {
        self.href
            .rsplit('/')
            .next()
            .unwrap_or(&self.href)
            .to_string()
    }
}

fn tag<'a>(block: &'a str, open: &str, close: &str) -> Option<&'a str> {
    let s = block.find(open)? + open.len();
    let e = block[s..].find(close)? + s;
    Some(&block[s..e])
}

fn attr<'a>(block: &'a str, elem: &str, name: &str) -> Option<&'a str> {
    let at = block.find(elem)? + elem.len();
    let rest = &block[at..];
    let key = format!("{name}=\"");
    let s = rest.find(&key)? + key.len();
    let e = rest[s..].find('"')? + s;
    Some(&rest[s..e])
}

/// Parse `primary.xml`.
///
/// Scanned rather than parsed with an XML library: the file is machine
/// generated by createrepo_c with a fixed shape, and the alternative is a
/// dependency for four fields. Every field that is missing makes the package
/// be skipped rather than half-read.
pub fn parse_primary(xml: &str) -> Vec<MediaPkg> {
    let mut out = Vec::new();
    for block in xml.split("<package type=\"rpm\">").skip(1) {
        let end = block.find("</package>").unwrap_or(block.len());
        let b = &block[..end];
        let (Some(name), Some(href), Some(src)) = (
            tag(b, "<name>", "</name>"),
            attr(b, "<location", "href"),
            tag(b, "<rpm:sourcerpm>", "</rpm:sourcerpm>"),
        ) else {
            continue;
        };
        out.push(MediaPkg {
            name: name.to_string(),
            href: href.to_string(),
            sourcerpm: src.to_string(),
            version: attr(b, "<version", "ver").unwrap_or("").to_string(),
            release: attr(b, "<version", "rel").unwrap_or("").to_string(),
        });
    }
    out
}

/// The media's `primary.xml`, decompressed.
pub fn primary_xml(isomnt: &Path) -> Result<String, String> {
    let dir = isomnt.join("RPMS/repodata");
    let f = fs::read_dir(&dir)
        .map_err(|e| format!("{}: {e}", dir.display()))?
        .flatten()
        .map(|e| e.path())
        .find(|p| {
            p.file_name()
                .map(|n| n.to_string_lossy().ends_with("primary.xml.gz"))
                .unwrap_or(false)
        })
        .ok_or_else(|| format!("no *-primary.xml.gz in {}", dir.display()))?;
    let raw = fs::read(&f).map_err(|e| format!("{}: {e}", f.display()))?;
    let plain = kconfig::gunzip(&raw)?;
    String::from_utf8(plain).map_err(|e| format!("{} is not UTF-8: {e}", f.display()))
}

/// Every package on the media built from `srpm`.
///
/// This is the replacement set. Derived, never hardcoded: `bpftool` belongs to
/// it and is not named `linux-`, and the set differs between kernel versions.
pub fn replacement_set(isomnt: &Path, srpm: &str) -> Result<Vec<MediaPkg>, String> {
    let xml = primary_xml(isomnt)?;
    let all = parse_primary(&xml);
    if all.is_empty() {
        return Err("the media's primary.xml listed no packages at all".to_string());
    }
    let mut hits: Vec<MediaPkg> = all.into_iter().filter(|p| p.sourcerpm == srpm).collect();
    hits.sort_by(|a, b| a.name.cmp(&b.name));
    if hits.is_empty() {
        return Err(format!(
            "no package on the media has SOURCERPM {srpm}; the input ISO was not built \
             from that kernel"
        ));
    }
    Ok(hits)
}

/// Build the new RPMS tree as an overlay over the read-only ISO tree.
///
/// Overlay rather than a copy: the media carries 1567 packages and only eight
/// change. The lower layer is the mounted ISO, so the input is unmodifiable by
/// construction.
pub fn build_repo(
    c: &mut Ctx,
    replace: &[MediaPkg],
    new_rpms: &[PathBuf],
) -> Result<PathBuf, String> {
    let base = c.spec.workdir.join("overlay");
    let (upper, work, merged) = (base.join("upper"), base.join("work"), base.join("merged"));
    for d in [&upper, &work, &merged] {
        fs::create_dir_all(d).map_err(|e| format!("{}: {e}", d.display()))?;
    }
    let lower = c.spec.isomnt().join("RPMS");
    if !ok("mountpoint", &["-q", &merged.to_string_lossy()]) {
        let opts = format!(
            "lowerdir={},upperdir={},workdir={}",
            lower.display(),
            upper.display(),
            work.display()
        );
        run(
            "mount",
            &[
                "-t",
                "overlay",
                "overlay",
                "-o",
                &opts,
                &merged.to_string_lossy(),
            ],
        )?;
        c.say(&format!(
            "  overlay of {} at {}",
            lower.display(),
            merged.display()
        ));
    }

    let archdir = merged.join(c.spec.arch.rpm());
    for p in replace {
        let old = merged.join(&p.href);
        if old.exists() {
            fs::remove_file(&old).map_err(|e| format!("removing {}: {e}", old.display()))?;
        }
    }
    let mut copied = 0;
    for r in new_rpms {
        let name = r
            .file_name()
            .map(|n| n.to_string_lossy().to_string())
            .unwrap_or_default();
        fs::copy(r, archdir.join(&name))
            .map_err(|e| format!("{name}: {e}"))
            .map(|_| ())?;
        copied += 1;
    }
    c.say(&format!(
        "  replaced {} package(s) with {copied} rebuilt one(s)",
        replace.len()
    ));

    let outdir = c.spec.workdir.join("repodata-out");
    let _ = fs::remove_dir_all(&outdir);
    fs::create_dir_all(&outdir).map_err(|e| format!("{}: {e}", outdir.display()))?;
    let log = c.spec.workdir.join("createrepo.log");
    super::run_logged(
        c,
        "createrepo_c",
        &[
            "--update",
            "--workers",
            "4",
            "--outputdir",
            &outdir.to_string_lossy(),
            &merged.to_string_lossy(),
        ],
        &log,
    )?;
    let rd = outdir.join("repodata");
    if !rd.join("repomd.xml").is_file() {
        return Err(format!(
            "createrepo_c produced no repomd.xml in {}",
            rd.display()
        ));
    }
    c.say(&format!("  regenerated metadata in {}", rd.display()));
    Ok(rd)
}

/// Unmount the overlay. Never fails the run: the artefacts are already written.
pub fn unmount_overlay(c: &mut Ctx) {
    let merged = c.spec.workdir.join("overlay/merged");
    if ok("mountpoint", &["-q", &merged.to_string_lossy()]) {
        match run("umount", &[&merged.to_string_lossy()]) {
            Ok(_) => c.say("  overlay unmounted"),
            Err(e) => c.say(&format!("  [warn] could not unmount the overlay: {e}")),
        }
    }
}

/// Assert the regenerated metadata describes the new kernel and not the old.
/// `replaced` is the REPLACEMENT SET - the packages this remaster rebuilt.
///
/// Staleness is keyed on that set, never on a name prefix. `linux-esx` and its
/// subpackages are built from their OWN SRPM, are deliberately not replaced,
/// and legitimately remain at the old version on the finished media. A
/// `starts_with("linux")` rule flags them and fails a perfectly good ISO.
pub fn assert_metadata(
    rd: &Path,
    new_vr: &str,
    old_vr: &str,
    replaced: &[String],
    expect: usize,
) -> Result<Vec<String>, String> {
    let f = fs::read_dir(rd)
        .map_err(|e| format!("{}: {e}", rd.display()))?
        .flatten()
        .map(|e| e.path())
        .find(|p| {
            p.file_name()
                .map(|n| n.to_string_lossy().ends_with("primary.xml.gz"))
                .unwrap_or(false)
        })
        .ok_or("the regenerated metadata has no primary.xml.gz")?;
    let xml = String::from_utf8(kconfig::gunzip(&fs::read(&f).map_err(|e| format!("{e}"))?)?)
        .map_err(|e| format!("{e}"))?;
    let pkgs = parse_primary(&xml);
    let new_hits: Vec<String> = pkgs
        .iter()
        .filter(|p| format!("{}-{}", p.version, p.release) == new_vr)
        .map(|p| p.basename())
        .collect();
    let stale: Vec<String> = pkgs
        .iter()
        .filter(|p| {
            format!("{}-{}", p.version, p.release) == old_vr
                && replaced.iter().any(|n| n == &p.name)
        })
        .map(|p| p.basename())
        .collect();
    if !stale.is_empty() {
        return Err(format!(
            "the regenerated metadata still lists {} replaced package(s) at the old \
             version {old_vr}: {}",
            stale.len(),
            stale.join(", ")
        ));
    }
    if new_hits.len() != expect {
        return Err(format!(
            "the metadata lists {} package(s) at {new_vr}, expected {expect}: {}",
            new_hits.len(),
            new_hits.join(", ")
        ));
    }
    Ok(new_hits)
}

/// The same assertion as `assert_metadata`, against a repodata directory
/// extracted from a finished ISO, where the package count is not known ahead of
/// time. Returns the packages found at the new version.
pub fn assert_metadata_dir(
    rd: &Path,
    new_vr: &str,
    old_vr: &str,
    replaced: &[String],
) -> Result<Vec<String>, String> {
    let f = fs::read_dir(rd)
        .map_err(|e| format!("{}: {e}", rd.display()))?
        .flatten()
        .map(|e| e.path())
        .find(|p| {
            p.file_name()
                .map(|n| n.to_string_lossy().ends_with("primary.xml.gz"))
                .unwrap_or(false)
        })
        .ok_or("no primary.xml.gz in the extracted repodata")?;
    let xml = String::from_utf8(kconfig::gunzip(&fs::read(&f).map_err(|e| format!("{e}"))?)?)
        .map_err(|e| format!("{e}"))?;
    let pkgs = parse_primary(&xml);
    // Keyed on the replacement set: linux-esx is a different SRPM, is not
    // replaced, and stays at the old version on good media.
    let stale: Vec<String> = pkgs
        .iter()
        .filter(|p| {
            format!("{}-{}", p.version, p.release) == old_vr
                && replaced.iter().any(|n| n == &p.name)
        })
        .map(|p| p.basename())
        .collect();
    if !stale.is_empty() {
        return Err(format!(
            "still lists {} replaced package(s) at the old version {old_vr}: {}",
            stale.len(),
            stale.join(", ")
        ));
    }
    let hits: Vec<String> = pkgs
        .iter()
        .filter(|p| format!("{}-{}", p.version, p.release) == new_vr)
        .map(|p| p.basename())
        .collect();
    if hits.is_empty() {
        return Err(format!("lists no package at all at {new_vr}"));
    }
    // Every package that was supposed to be replaced must be present at the
    // new version, or the media carries an unresolvable Requires.
    let missing: Vec<&String> = replaced
        .iter()
        .filter(|n| {
            !pkgs
                .iter()
                .any(|p| &p.name == *n && format!("{}-{}", p.version, p.release) == new_vr)
        })
        .collect();
    if !missing.is_empty() {
        return Err(format!(
            "{} replaced package(s) are absent at {new_vr}: {}",
            missing.len(),
            missing
                .iter()
                .map(|s| s.as_str())
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }
    Ok(hits)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A primary.xml in the shape createrepo_c writes, with the three cases
    /// that matter: a kernel subpackage, `bpftool` (same SRPM, different name)
    /// and `linux-esx` (a DIFFERENT SRPM, so not ours to replace).
    const XML: &str = r#"<?xml version="1.0"?>
<metadata packages="4">
<package type="rpm">
  <name>linux</name>
  <version epoch="0" ver="6.12.109" rel="3.ph5"/>
  <location href="aarch64/linux-6.12.109-3.ph5.aarch64.rpm"/>
  <format><rpm:sourcerpm>linux-6.12.109-3.ph5.src.rpm</rpm:sourcerpm></format>
</package>
<package type="rpm">
  <name>bpftool</name>
  <version epoch="0" ver="6.12.109" rel="3.ph5"/>
  <location href="aarch64/bpftool-6.12.109-3.ph5.aarch64.rpm"/>
  <format><rpm:sourcerpm>linux-6.12.109-3.ph5.src.rpm</rpm:sourcerpm></format>
</package>
<package type="rpm">
  <name>linux-esx</name>
  <version epoch="0" ver="6.12.109" rel="3.ph5"/>
  <location href="aarch64/linux-esx-6.12.109-3.ph5.aarch64.rpm"/>
  <format><rpm:sourcerpm>linux-esx-6.12.109-3.ph5.src.rpm</rpm:sourcerpm></format>
</package>
<package type="rpm">
  <name>vim</name>
  <version epoch="0" ver="9.0" rel="1.ph5"/>
  <location href="aarch64/vim-9.0-1.ph5.aarch64.rpm"/>
  <format><rpm:sourcerpm>vim-9.0-1.ph5.src.rpm</rpm:sourcerpm></format>
</package>
</metadata>
"#;

    /// The set is every package built from the kernel SRPM - which includes
    /// bpftool, whose name gives no hint, and excludes linux-esx, which is a
    /// different SRPM and therefore not ours to replace.
    #[test]
    fn the_replacement_set_is_every_package_sharing_the_kernel_srpm_including_bpftool() {
        let pkgs = parse_primary(XML);
        assert_eq!(pkgs.len(), 4);

        let ours: Vec<&MediaPkg> = pkgs
            .iter()
            .filter(|p| p.sourcerpm == "linux-6.12.109-3.ph5.src.rpm")
            .collect();
        let names: Vec<&str> = ours.iter().map(|p| p.name.as_str()).collect();
        assert!(
            names.contains(&"bpftool"),
            "a name-based rule would miss it: {names:?}"
        );
        assert!(names.contains(&"linux"));
        assert!(
            !names.contains(&"linux-esx"),
            "linux-esx is a different SRPM and must not be replaced: {names:?}"
        );
        assert!(!names.contains(&"vim"));
        assert_eq!(ours.len(), 2);

        let l = ours.iter().find(|p| p.name == "linux").unwrap();
        assert_eq!(l.href, "aarch64/linux-6.12.109-3.ph5.aarch64.rpm");
        assert_eq!(l.basename(), "linux-6.12.109-3.ph5.aarch64.rpm");
        assert_eq!(format!("{}-{}", l.version, l.release), "6.12.109-3.ph5");
    }

    /// The metadata check has to fail when the old kernel survives - that is
    /// the failure it exists to catch - and pass when it does not.
    #[test]
    fn stale_kernel_metadata_fails_the_repo_assertion() {
        let d = std::env::temp_dir().join(format!("shk-repo-{}", std::process::id()));
        let _ = fs::remove_dir_all(&d);
        fs::create_dir_all(&d).unwrap();

        // Build a gzip member the same way the ikconfig test does: a single
        // stored deflate block, so no compressor is needed to make a fixture.
        let gz = |payload: &[u8]| -> Vec<u8> {
            let mut v = vec![0x1f, 0x8b, 0x08, 0x00, 0, 0, 0, 0, 0x00, 0x03];
            v.push(0x01);
            let len = payload.len() as u16;
            v.extend_from_slice(&len.to_le_bytes());
            v.extend_from_slice(&(!len).to_le_bytes());
            v.extend_from_slice(payload);
            v.extend_from_slice(&[0, 0, 0, 0]);
            v.extend_from_slice(&(payload.len() as u32).to_le_bytes());
            v
        };
        fs::write(d.join("a-primary.xml.gz"), gz(XML.as_bytes())).unwrap();

        let replaced: Vec<String> = vec!["linux".into(), "bpftool".into()];

        // XML still carries the old 6.12.109-3.ph5 kernel: the assertion must
        // refuse it and name what it found.
        let e = assert_metadata(&d, "6.12.109-4.azure.ph5", "6.12.109-3.ph5", &replaced, 2)
            .unwrap_err();
        assert!(e.contains("at the old version"), "{e}");
        assert!(e.contains("linux-6.12.109-3.ph5.aarch64.rpm"), "{e}");

        // Negative control: with the replaced packages moved to the new
        // version, the same call passes, so the check is not vacuous.
        let fixed = XML
            .replace(
                "<name>linux</name>\n  <version epoch=\"0\" ver=\"6.12.109\" rel=\"3.ph5\"/>\n  <location href=\"aarch64/linux-6.12.109-3.ph5.aarch64.rpm\"/>",
                "<name>linux</name>\n  <version epoch=\"0\" ver=\"6.12.109\" rel=\"4.azure.ph5\"/>\n  <location href=\"aarch64/linux-6.12.109-4.azure.ph5.aarch64.rpm\"/>",
            )
            .replace(
                "<name>bpftool</name>\n  <version epoch=\"0\" ver=\"6.12.109\" rel=\"3.ph5\"/>\n  <location href=\"aarch64/bpftool-6.12.109-3.ph5.aarch64.rpm\"/>",
                "<name>bpftool</name>\n  <version epoch=\"0\" ver=\"6.12.109\" rel=\"4.azure.ph5\"/>\n  <location href=\"aarch64/bpftool-6.12.109-4.azure.ph5.aarch64.rpm\"/>",
            );
        fs::write(d.join("a-primary.xml.gz"), gz(fixed.as_bytes())).unwrap();
        let ok =
            assert_metadata(&d, "6.12.109-4.azure.ph5", "6.12.109-3.ph5", &replaced, 2).unwrap();
        assert_eq!(ok.len(), 2);

        // THE REGRESSION: linux-esx is still at 6.12.109-3.ph5 in that same
        // XML, legitimately - it is built from its own SRPM and is not ours to
        // replace. A name-prefix rule flagged it and failed a good ISO.
        assert!(
            !ok.iter().any(|n| n.contains("esx")),
            "linux-esx is not in the replacement set: {ok:?}"
        );
        let dir_ok = assert_metadata_dir(&d, "6.12.109-4.azure.ph5", "6.12.109-3.ph5", &replaced)
            .expect("linux-esx at the old version must not be reported stale");
        assert_eq!(dir_ok.len(), 2, "{dir_ok:?}");
        let _ = fs::remove_dir_all(&d);
    }

    /// The replacement set against REAL media, which is where a name-based
    /// rule actually bites: `bpftool` shares the kernel SRPM and is not called
    /// `linux-` anything, and it carries `Requires: linux-tools = V-R`, so
    /// leaving it behind puts an unresolvable dependency on the ISO.
    ///
    /// Skipped unless `MC_TEST_ISO_MOUNT` names a mounted Photon ISO, so the
    /// default suite needs no media.
    #[test]
    fn the_replacement_set_on_real_media_includes_bpftool_and_excludes_the_esx_flavour() {
        let Ok(mnt) = std::env::var("MC_TEST_ISO_MOUNT") else {
            return;
        };
        let mnt = std::path::PathBuf::from(mnt);
        if !mnt.join("RPMS/repodata").is_dir() {
            return;
        }
        let xml = primary_xml(&mnt).expect("the media must have readable repodata");
        let all = parse_primary(&xml);
        assert!(
            all.len() > 1000,
            "only {} packages parsed from real media",
            all.len()
        );

        // Derive the kernel SRPM from the media rather than naming it.
        let linux = all
            .iter()
            .find(|p| p.name == "linux")
            .expect("the media must carry a linux package");
        let srpm = linux.sourcerpm.clone();

        let set = replacement_set(&mnt, &srpm).unwrap();
        let mut names: Vec<&str> = set.iter().map(|p| p.name.as_str()).collect();
        names.sort_unstable();

        assert!(
            names.contains(&"bpftool"),
            "bpftool shares the kernel SRPM; a name-based rule misses it: {names:?}"
        );
        assert!(
            !names.contains(&"linux-esx"),
            "linux-esx is built from its OWN SRPM and must not be replaced: {names:?}"
        );
        // Every member really does share the SRPM - the filter is the whole point.
        assert!(set.iter().all(|p| p.sourcerpm == srpm), "{names:?}");
        // and each names a real file on the media
        for p in &set {
            assert!(
                mnt.join("RPMS").join(&p.href).is_file(),
                "{} is listed in the metadata but absent from the media",
                p.href
            );
        }
        eprintln!("replacement set from {srpm}: {names:?}");
    }

    /// A package whose fields cannot all be read is skipped rather than
    /// half-parsed into a wrong replacement decision.
    #[test]
    fn a_package_block_missing_a_field_is_skipped_not_half_read() {
        let broken = r#"<metadata>
<package type="rpm">
  <name>linux</name>
  <version epoch="0" ver="6.12.109" rel="3.ph5"/>
  <format><rpm:sourcerpm>linux-6.12.109-3.ph5.src.rpm</rpm:sourcerpm></format>
</package>
</metadata>"#;
        // no <location href>: nothing to replace, so nothing is claimed
        assert!(parse_primary(broken).is_empty());
    }
}
