/* sourceforge.c — sourceforge.net release detection (M35).
 *
 * Ports photonos-package-report.ps1 L 3459-3535 (the URL derivation +
 * name extraction half of the sourceforge branch). The filtering and
 * version comparison that follow are done by check_urlhealth.c's
 * existing name pipeline, so this file only:
 *   1. derives the SourceTagURL (strip-sequence + split[0], plus the
 *      per-spec overrides at PS L 3476-3495), and
 *   2. fetches that URL and extracts the version directory names from
 *      the embedded `net.sf.files = {...}};` JS blob, stripping the
 *      archive extensions PS removes at L 3532-3535.
 */
#include "pr_sourceforge.h"

#include <curl/curl.h>
#define PCRE2_CODE_UNIT_WIDTH 8
#include <pcre2.h>

#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>

#define BODY_CAP_BYTES (16 * 1024 * 1024)   /* SF listing pages are large */

/* Case-insensitive whole-spec match helper (PS uses -ilike with no
 * wildcards here, i.e. plain case-insensitive equality). */
static int spec_is(const char *spec, const char *name)
{
    return spec != NULL && strcasecmp(spec, name) == 0;
}

char *pr_sourceforge_tag_url(const char *spec, const char *source0)
{
    if (source0 == NULL || source0[0] == '\0') return NULL;

    /* Per-spec overrides take precedence (PS L 3476-3495). */
    if (spec) {
        const char *ov = NULL;
        if      (spec_is(spec, "docbook-xsl.spec")) ov = "https://sourceforge.net/projects/docbook/files/docbook-xsl";
        else if (spec_is(spec, "expect.spec"))      ov = "https://sourceforge.net/projects/expect/files/Expect";
        else if (spec_is(spec, "fakeroot-ng.spec")) ov = "https://sourceforge.net/projects/fakerootng/files/fakeroot-ng";
        else if (spec_is(spec, "libpng.spec"))      ov = "https://sourceforge.net/projects/libpng/files/libpng16";
        else if (spec_is(spec, "nfs-utils.spec"))   ov = "https://sourceforge.net/projects/nfs/files/nfs-utils";
        else if (spec_is(spec, "openipmi.spec"))    ov = "https://sourceforge.net/projects/openipmi/files/OpenIPMI%202.0%20Library/";
        else if (spec_is(spec, "procps-ng.spec"))   ov = "https://sourceforge.net/projects/procps-ng/files/Production/";
        else if (spec_is(spec, "tcl.spec"))         ov = "https://sourceforge.net/projects/tcl/files/Tcl";
        else if (spec_is(spec, "unzip.spec"))       ov = "https://sourceforge.net/projects/infozip/files/UnZip%206.x%20%28latest%29/UnZip%206.0/";
        else if (spec_is(spec, "xmlstarlet.spec"))  ov = "https://sourceforge.net/projects/xmlstar/files/xmlstarlet";
        else if (spec_is(spec, "zip.spec"))         ov = "https://sourceforge.net/projects/infozip/files/Zip%203.x%20%28latest%29/3.0/";
        if (ov) return strdup(ov);
    }

    /* Autogenerated derivation (PS L 3462-3475): drop scheme + a fixed
     * sequence of substrings, then take the first path segment. The
     * order matters and mirrors PS line-for-line. */
    char *s = strdup(source0);
    if (!s) return NULL;

    static const char *const drops[] = {
        "http://", "https://",
        "sourceforge.net/", "downloads.project/", "projects/",
        "prdownloads.", "downloads.", "download.",
        "gkernel/files/", "sourceforge/",
        NULL,
    };
    for (int i = 0; drops[i]; i++) {
        const char *d = drops[i];
        size_t dl = strlen(d);
        char *hit;
        while ((hit = strstr(s, d)) != NULL) {
            memmove(hit, hit + dl, strlen(hit + dl) + 1);
        }
    }

    /* tmpName = first segment before '/'. */
    char *slash = strchr(s, '/');
    if (slash) *slash = '\0';

    char *url = NULL;
    if (asprintf(&url, "https://sourceforge.net/projects/%s/files/%s", s, s) < 0)
        url = NULL;
    free(s);
    return url;
}

struct body_buf {
    char  *data;
    size_t len;
    size_t cap;
    int    overflow;
};

static size_t body_write_cb(void *ptr, size_t size, size_t nmemb, void *userdata)
{
    struct body_buf *b = (struct body_buf *)userdata;
    size_t n = size * nmemb;
    if (b->overflow) return n;
    if (b->len + n > BODY_CAP_BYTES) { b->overflow = 1; return n; }
    if (b->len + n > b->cap) {
        size_t newcap = b->cap ? b->cap * 2 : 65536;
        while (newcap < b->len + n) newcap *= 2;
        char *p = (char *)realloc(b->data, newcap);
        if (!p) { b->overflow = 1; return n; }
        b->data = p;
        b->cap = newcap;
    }
    memcpy(b->data + b->len, ptr, n);
    b->len += n;
    return n;
}

static pcre2_code     *RE_NAME;
static pthread_once_t  g_name_once = PTHREAD_ONCE_INIT;

static void init_re_name(void)
{
    int        err = 0;
    PCRE2_SIZE off = 0;
    RE_NAME = pcre2_compile((PCRE2_SPTR)"\"name\"\\s*:\\s*\"([^\"]*)\"",
                            PCRE2_ZERO_TERMINATED, 0, &err, &off, NULL);
    if (!RE_NAME) {
        PCRE2_UCHAR ebuf[256];
        pcre2_get_error_message(err, ebuf, sizeof ebuf);
        fprintf(stderr, "sourceforge.c: re_compile failed: %s\n", (char *)ebuf);
        abort();
    }
}

static void strip_archive_ext(char *s)
{
    /* PS L 3532-3535: drop the four archive extensions (anywhere). */
    static const char *const exts[] = {
        ".tar.gz", ".tar.bz2", ".tar.xz", ".tar.lz", NULL,
    };
    for (int e = 0; exts[e]; e++) {
        size_t el = strlen(exts[e]);
        char *hit;
        while ((hit = strstr(s, exts[e])) != NULL) {
            memmove(hit, hit + el, strlen(hit + el) + 1);
        }
    }
}

int pr_sourceforge_fetch_names(const char *url, char ***names_out, size_t *n_out)
{
    if (url == NULL || names_out == NULL || n_out == NULL) return -1;
    *names_out = NULL;
    *n_out = 0;

    struct body_buf body = {0};
    CURL *c = curl_easy_init();
    if (!c) return -1;
    curl_easy_setopt(c, CURLOPT_URL,             url);
    curl_easy_setopt(c, CURLOPT_FOLLOWLOCATION,  1L);
    curl_easy_setopt(c, CURLOPT_TIMEOUT_MS,      20000L);
    curl_easy_setopt(c, CURLOPT_USERAGENT,       "PowerShell");
    curl_easy_setopt(c, CURLOPT_WRITEFUNCTION,   body_write_cb);
    curl_easy_setopt(c, CURLOPT_WRITEDATA,       &body);
    curl_easy_setopt(c, CURLOPT_ACCEPT_ENCODING, "");
    CURLcode rc = curl_easy_perform(c);
    long status = 0;
    if (rc == CURLE_OK) curl_easy_getinfo(c, CURLINFO_RESPONSE_CODE, &status);
    curl_easy_cleanup(c);

    if (rc != CURLE_OK || status < 200 || status >= 300 || body.overflow || body.len == 0) {
        free(body.data);
        return -1;
    }

    /* Isolate the `net.sf.files = {...}};` blob (PS L 3497). Bounding
     * the regex to this region avoids matching "name" elsewhere on the
     * page. */
    const char *start = NULL;
    {
        static const char *MARK = "net.sf.files = {";
        char *m = memmem(body.data, body.len, MARK, strlen(MARK));
        if (m) start = m + strlen(MARK);
    }
    size_t region_len;
    const char *region;
    if (start) {
        const char *end = memmem(start, body.len - (size_t)(start - body.data), "}};", 3);
        region = start;
        region_len = end ? (size_t)(end - start) : body.len - (size_t)(start - body.data);
    } else {
        free(body.data);
        return -1;
    }

    pthread_once(&g_name_once, init_re_name);
    pcre2_match_data *md = pcre2_match_data_create_from_pattern(RE_NAME, NULL);
    if (!md) { free(body.data); return -1; }

    size_t cap = 32, n = 0;
    char **names = (char **)malloc(cap * sizeof *names);
    if (!names) { pcre2_match_data_free(md); free(body.data); return -1; }

    PCRE2_SIZE offset = 0;
    while (offset < region_len) {
        int hits = pcre2_match(RE_NAME, (PCRE2_SPTR)region, region_len,
                                offset, 0, md, NULL);
        if (hits < 0) break;
        PCRE2_SIZE *ov = pcre2_get_ovector_pointer(md);
        PCRE2_SIZE vs = ov[2], ve = ov[3];
        if (vs != PCRE2_UNSET && ve > vs) {
            size_t vlen = (size_t)(ve - vs);
            char *val = (char *)malloc(vlen + 1);
            if (val) {
                memcpy(val, region + vs, vlen);
                val[vlen] = '\0';
                strip_archive_ext(val);
                if (n == cap) {
                    cap *= 2;
                    char **p = (char **)realloc(names, cap * sizeof *names);
                    if (!p) { free(val); break; }
                    names = p;
                }
                names[n++] = val;
            }
        }
        offset = ov[1];
        if (offset <= ov[0]) offset++;
    }

    pcre2_match_data_free(md);
    free(body.data);

    if (n == 0) { free(names); return -1; }
    *names_out = names;
    *n_out = n;
    return 0;
}
