#!/bin/sh
# csv-to-c-string.sh — wrap raw CSV (stdin) into a C string literal header.
#
# Output (stdout):
#
#   /* AUTO-GENERATED by tools/csv-to-c-string.sh — DO NOT EDIT. */
#   #ifndef PR_SOURCE0_LOOKUP_DATA_H
#   #define PR_SOURCE0_LOOKUP_DATA_H
#   static const char *const pr_source0_lookup_csv =
#       "specfile,Source0Lookup,...\n"
#       "abseil-cpp.spec,...\n"
#       ...
#       "zstd.spec,...\n"
#       ;
#   #endif
#
# Each CSV input line becomes ONE C string literal terminated by an
# embedded `\n`. Adjacent string literals are concatenated by the C
# compiler.
#
# Invariants (ADR-0005):
#   - POSIX shell + awk only. No Python, no Perl.
#   - Preserves UTF-8 byte stream (high bytes pass through unchanged).
#   - Escapes only the two C-string-meta characters and ASCII control
#     codes < 0x20. Tab, however, is emitted as `\t` because it occurs
#     in real CSV cells (rare).
#
# Usage:
#   extract-source0-lookup.sh /path/to/ps1 | csv-to-c-string.sh > source0_lookup_data.h

set -eu

awk_prog=$(mktemp)
trap 'rm -f "$awk_prog"' EXIT INT TERM

cat > "$awk_prog" <<'AWKEOF'
BEGIN {
    print "/* AUTO-GENERATED by tools/csv-to-c-string.sh from"
    print " *   tools/extract-source0-lookup.sh ../photonos-package-report.ps1"
    print " * DO NOT EDIT — regenerate via the CMake build. */"
    print "#ifndef PR_SOURCE0_LOOKUP_DATA_H"
    print "#define PR_SOURCE0_LOOKUP_DATA_H"
    print "static const char *const pr_source0_lookup_csv ="
}
{
    line = $0
    # Order matters: backslash first so we do not double-escape the
    # backslashes we introduce.
    gsub(/\\/, "\\\\", line)
    gsub(/"/,  "\\\"", line)
    gsub(/\t/, "\\t",  line)
    # Other ASCII controls are vanishingly rare in the CSV body; if any
    # appear, this script intentionally leaves them in place so a build
    # error surfaces upstream instead of silently mangling the bytes.
    printf("    \"%s\\n\"\n", line)
}
END {
    print "    ;"
    print "#endif /* PR_SOURCE0_LOOKUP_DATA_H */"
}
AWKEOF

awk -f "$awk_prog"
