#!/usr/bin/env python3
# diff_analyzer.py — produce per-branch C↔PS .prn diff markdown reports.
#
# Phase M task M06 (FRD-017 §2.2).
#
# Reads two .prn files per branch (PS-side, C-side) and emits a markdown
# report that joins on Spec (col 1) and buckets each divergent row by
# the tuple of columns where the two sides disagree. Volatile columns
# (UrlHealth = 4, HealthUpdateURL = 7) are excluded from the signature
# per ADR-0006 but their underlying differences are still surfaced in
# the example pairs.
#
# Usage:
#   tools/diff_analyzer.py <ps-prn-dir> <c-prn-dir> <out-md-dir>
#
# - <ps-prn-dir> directory containing photonos-urlhealth-<branch>_<ts>.prn
#   from the PS-side workflow's parity snapshot.
# - <c-prn-dir>  directory containing matching C-side .prn files
#   (e.g. unpacked artifact c-side-prn-<run_id>).
# - <out-md-dir> destination for diff-c-vs-ps-photon-<branch>.md files.
#
# Branches scanned: 3.0, 4.0, 5.0, 6.0, common, dev, master. Branches
# absent on either side are skipped with a warning.
#
# Exit:
#   0 — all branches with paired data processed
#   1 — usage error / missing dir
import csv
import os
import sys
from collections import defaultdict

COL_NAMES = [
    "Spec", "Source0_original", "Source0_modified",
    "UrlHealth", "UpdateAvailable", "UpdateURL",
    "HealthUpdateURL", "Name", "SHAName",
    "UpdateDownloadName", "warning", "ArchivationDate",
]
VOLATILE = {3, 6}  # UrlHealth, HealthUpdateURL (0-indexed)
BRANCHES = ("3.0", "4.0", "5.0", "6.0", "common", "dev", "master")


def read_prn(path):
    """Return dict spec → 12-col row list."""
    out = {}
    with open(path) as f:
        reader = csv.reader(f)
        next(reader, None)  # header
        for r in reader:
            r = r + [""] * (12 - len(r))
            out[r[0]] = r[:12]
    return out


def diff_signature(ps_row, c_row):
    """Tuple of column indices where rows differ, ignoring volatile."""
    return tuple(i for i in range(12) if i not in VOLATILE and ps_row[i] != c_row[i])


def cause_label(diffs):
    if not diffs:
        return "byte-identical (volatile-only)"
    return ",".join(COL_NAMES[i] for i in diffs)


def find_branch_prn(d, branch):
    """Latest photonos-urlhealth-<branch>_<ts>.prn in d, or None."""
    if not os.path.isdir(d):
        return None
    prefix = f"photonos-urlhealth-{branch}_"
    cands = sorted(f for f in os.listdir(d) if f.startswith(prefix) and f.endswith(".prn"))
    return os.path.join(d, cands[-1]) if cands else None


def analyze(branch, ps_path, c_path, out_md):
    ps = read_prn(ps_path)
    c = read_prn(c_path)
    ps_only = sorted(set(ps) - set(c))
    c_only = sorted(set(c) - set(ps))
    common = sorted(set(ps) & set(c))

    sig_specs = defaultdict(list)
    sig_examples = {}
    identical = 0
    for spec in common:
        sig = diff_signature(ps[spec], c[spec])
        if not sig:
            identical += 1
            continue
        sig_specs[sig].append(spec)
        if sig not in sig_examples:
            sig_examples[sig] = (ps[spec], c[spec])

    divergent = sum(len(v) for v in sig_specs.values())

    with open(out_md, "w") as f:
        f.write(f"# C ↔ PS PRN diff — photon-{branch}\n\n")
        f.write(f"*Auto-generated by `tools/diff_analyzer.py`. Regenerate after every paired run; see Phase M task M06.*\n\n")
        f.write(f"**PS prn:** `{ps_path}`\n")
        f.write(f"**C prn:**  `{c_path}`\n\n")
        f.write("## Summary\n\n")
        f.write("| Metric | Count |\n|---|---|\n")
        f.write(f"| PS rows | {len(ps)} |\n")
        f.write(f"| C rows  | {len(c)} |\n")
        f.write(f"| Common specs (both sides) | {len(common)} |\n")
        f.write(f"| Specs only in PS | {len(ps_only)} |\n")
        f.write(f"| Specs only in C  | {len(c_only)} |\n")
        f.write(f"| Common: byte-identical (excl. volatile) | {identical} |\n")
        f.write(f"| Common: at least one non-volatile col differs | {divergent} |\n\n")

        if ps_only:
            f.write(f"## Specs only in PS — {len(ps_only)}\n\n")
            f.write("C didn't emit a row for these. Most-likely cause: spec basename collision (PS handles duplicate basenames from subrelease subdirs, C does not yet) or parse_directory divergence.\n\n")
            for s in ps_only[:30]:
                f.write(f"- `{s}`\n")
            if len(ps_only) > 30:
                f.write(f"- ... +{len(ps_only) - 30} more\n")
            f.write("\n")

        if c_only:
            f.write(f"## Specs only in C — {len(c_only)}\n\n")
            f.write("C emitted a row PS didn't. Should never happen at parity-converge. Investigate.\n\n")
            for s in c_only[:30]:
                f.write(f"- `{s}`\n")
            if len(c_only) > 30:
                f.write(f"- ... +{len(c_only) - 30} more\n")
            f.write("\n")

        f.write("## Root-cause categories (diff-signature buckets)\n\n")
        f.write("A diff-signature is the set of non-volatile columns where PS and C disagree for at least one spec. Same signature → same root cause (or close). Volatile cols 4 (`UrlHealth`) and 7 (`HealthUpdateURL`) are excluded from the signature per ADR-0006.\n\n")
        f.write("| Count | Diff signature | Sample spec | Sample col | PS value | C value |\n")
        f.write("|---|---|---|---|---|---|\n")
        for sig, specs in sorted(sig_specs.items(), key=lambda x: (-len(x[1]), x[0])):
            label = cause_label(sig)
            ps_ex, c_ex = sig_examples[sig]
            # Pick the first column in the signature with differing value
            sample_col = sig[0]
            ps_v = (ps_ex[sample_col] or "")[:60].replace("|", "\\|").replace("\n", " ")
            c_v = (c_ex[sample_col] or "")[:60].replace("|", "\\|").replace("\n", " ")
            f.write(f"| {len(specs)} | `{label}` | `{specs[0]}` | `{COL_NAMES[sample_col]}` | `{ps_v}` | `{c_v}` |\n")

        f.write("\n## Top 8 buckets — full affected-spec lists\n\n")
        for sig, specs in sorted(sig_specs.items(), key=lambda x: -len(x[1]))[:8]:
            label = cause_label(sig)
            f.write(f"### `{label}` — {len(specs)} specs\n\n")
            for s in specs[:50]:
                f.write(f"- `{s}`\n")
            if len(specs) > 50:
                f.write(f"- ... +{len(specs) - 50} more\n")
            f.write("\n")

    return len(sig_specs), divergent, len(ps_only), len(c_only)


def main():
    if len(sys.argv) != 4:
        sys.stderr.write("usage: diff_analyzer.py <ps-prn-dir> <c-prn-dir> <out-md-dir>\n")
        return 1
    ps_dir, c_dir, out_dir = sys.argv[1:]
    if not os.path.isdir(ps_dir):
        sys.stderr.write(f"PS dir not a directory: {ps_dir}\n"); return 1
    if not os.path.isdir(c_dir):
        sys.stderr.write(f"C dir not a directory: {c_dir}\n"); return 1
    os.makedirs(out_dir, exist_ok=True)

    total = 0
    for branch in BRANCHES:
        ps_p = find_branch_prn(ps_dir, branch)
        c_p = find_branch_prn(c_dir, branch)
        if not ps_p or not c_p:
            sys.stderr.write(f"skip {branch}: ps={ps_p} c={c_p}\n")
            continue
        out = os.path.join(out_dir, f"diff-c-vs-ps-photon-{branch}.md")
        nsigs, ndiv, npso, ncso = analyze(branch, ps_p, c_p, out)
        sys.stderr.write(f"  {branch:8s}  signatures={nsigs:3d}  divergent={ndiv:5d}  ps-only={npso:4d}  c-only={ncso:4d}  -> {out}\n")
        total += 1
    return 0 if total else 1


if __name__ == "__main__":
    sys.exit(main())
