#!/bin/sh
# generate-hook-dispatch.sh — scan src/hooks/*.c, emit dispatch table.
#
# Each hook file must declare its canonical spec basename via the
# annotation:
#
#     /* SPEC: <spec-basename>.spec */
#
# anywhere in the file (conventionally the first line). The function
# name is derived from the source file basename:
#
#     src/hooks/inih.c             -> hook_inih_spec
#     src/hooks/open_vm_tools.c    -> hook_open_vm_tools_spec
#     src/hooks/samba_client.c     -> hook_samba_client_spec
#
# This script writes a single C translation unit containing:
#
#     #include "pr_hook.h"
#     extern int hook_inih_spec(pr_task_t *, pr_state_t *);
#     extern int hook_open_vm_tools_spec(pr_task_t *, pr_state_t *);
#     ...
#     const pr_hook_entry_t pr_hook_dispatch[] = {
#         { "inih.spec",          hook_inih_spec },
#         { "open-vm-tools.spec", hook_open_vm_tools_spec },
#         ...
#     };
#     const size_t pr_hook_dispatch_count = N;
#
# Entries are sorted by spec basename strcmp order so pr_hooks_find()
# can bsearch.
#
# Usage:
#   generate-hook-dispatch.sh <hooks-dir> > pr_hook_dispatch.c

set -eu

if [ $# -ne 1 ]; then
    echo "usage: $0 <hooks-dir>" >&2
    exit 2
fi
hooks_dir=$1
if [ ! -d "$hooks_dir" ]; then
    echo "$0: not a directory: $hooks_dir" >&2
    exit 2
fi

awk_prog=$(mktemp)
trap 'rm -f "$awk_prog"' EXIT INT TERM

# Phase 1: collect (spec, fn) tuples, one per line, TSV.
list=$(mktemp)
trap 'rm -f "$awk_prog" "$list"' EXIT INT TERM

for f in "$hooks_dir"/*.c; do
    [ -e "$f" ] || continue
    base=$(basename "$f" .c)
    fn="hook_${base}_spec"
    spec=$(awk '
        /\/\* SPEC:[ \t]*[^* ]+\.spec[ \t]*\*\// {
            if (match($0, /SPEC:[ \t]*[^* ]+\.spec/)) {
                tok = substr($0, RSTART + 5, RLENGTH - 5)
                # strip leading whitespace
                sub(/^[ \t]+/, "", tok)
                print tok
                exit
            }
        }
    ' "$f")
    if [ -z "$spec" ]; then
        echo "$0: $f missing /* SPEC: <name>.spec */ annotation" >&2
        exit 3
    fi
    printf '%s\t%s\n' "$spec" "$fn" >> "$list"
done

# Phase 2: sort by spec column, then emit the C source.
sorted=$(mktemp)
trap 'rm -f "$awk_prog" "$list" "$sorted"' EXIT INT TERM
if [ -s "$list" ]; then
    LC_ALL=C sort -t '	' -k1,1 "$list" > "$sorted"
fi

cat <<'HEAD'
/* AUTO-GENERATED by tools/generate-hook-dispatch.sh — DO NOT EDIT.
 * Regenerated on every build from the hook sources under src/hooks
 * by the CMake custom command in CMakeLists.txt. */
#include "pr_hook.h"

#include <stddef.h>

HEAD

if [ -s "$sorted" ]; then
    # Extern declarations
    awk -F '\t' '{ printf "extern int %s(pr_task_t *, pr_state_t *);\n", $2 }' "$sorted"
    printf '\n'
    printf 'const pr_hook_entry_t pr_hook_dispatch[] = {\n'
    awk -F '\t' '{ printf "    { \"%s\", %s },\n", $1, $2 }' "$sorted"
    printf '};\n'
    count=$(wc -l < "$sorted")
    printf 'const size_t pr_hook_dispatch_count = %s;\n' "$count"
else
    printf 'const pr_hook_entry_t pr_hook_dispatch[] = { { 0, 0 } };\n'
    printf 'const size_t pr_hook_dispatch_count = 0;\n'
fi
